### ISSUE TITLE
Missing file: nodrives.reg

### ISSUE THREAD

**Issue by Augustus78** [7heMC/SteadierState#2]
Hi.

in buildpe.cmd a file nodrives.reg is used. However, this file ist not here at github. Can you please add it?

Greetings
Augustus

**Comment by 7heMC** [comment]
Thanks for pointing this out. I've removed the mention of that file from buildpe.cmd because the file is only needed if using the firstrun.cmd. Also, due to the nature of the nodrives.reg file, it must be created after install, which is already occurring when firstrun.cmd is executed.

https://github.com/7heMC/SteadierState/commit/3b1fc84b05955d0b9253bf0057bc6f3e3655bc6c
